# -*- coding: utf-8 -*-
"""計算累積數字.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VaDFG1XWF2EIHuOntGydbrC_xQeSm3IL
"""

Q1 = 26295929

Q2 = 27668242

Q3 = 27002993

Q4 = 28347871

ACC_Q1 = Q1
print(ACC_Q1)

ACC_Q2 = Q1 + Q2
print(ACC_Q2)

ACC_Q3 = Q1 + Q2 + Q3
print(ACC_Q3)

ACC_Q4 = Q1 + Q2 + Q3 + Q4
print(ACC_Q4)